services:
  db:
    image: postgres:16-alpine
    container_name: stock_intelligence_db
    environment:
      - POSTGRES_DB=stock_intelligence
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  pgdata:
