services:
  db:
    image: postgres:16-alpine
    container_name: stock_intelligence_db
    environment:
      - POSTGRES_DB=stock_intelligence
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
